#!/usr/bin/env bash

function usage_exit() {
  echo "Usage: $0 [-p port] [up|down]" 1>&2
  exit 1
}

function serve_up() {
  port=$1
  if [ -e "$cidfile" ]; then
    echo "Already running" 1>&2
    exit 4
  else
    docker run -d -v $(pwd):/usr/share/nginx/html:ro -p $port:80 nginx > $cidfile &&
    echo -e "Start up successfully in localhost:$port"
  fi
}

function serve_down() {
  port=$1
  if [ -r "$cidfile" ]; then
    cid=$(head -n 1 $cidfile)
    docker stop $cid > /dev/null && \
    docker rm $cid > /dev/null && \
    rm $cidfile && \
    echo "Shut down successfully"
  else
    echo "Cannot read: $cidfile" 1>&2
    exit 3
  fi
}

cidfile=.serve

port=80
while getopts p: OPT
do
  case $OPT in
    p)
      port=$OPTARG
      ;;
    \?) usage_exit
      ;;
  esac
done

shift $((OPTIND - 1))

if [ -z "$1" ]; then
  usage_exit
elif [ "$1" = up ]; then
  serve_up $port
elif [ "$1" = down ]; then
  serve_down $port
else
  echo "Unknown command: $1" 1>&2
  exit 2
fi
